// <auto-generated />
using CaixaEletronico.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaixaEletronico.API.Data.Migrations
{
    [DbContext(typeof(CaixaEletronicoContext))]
    [Migration("20210426233817_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CaixaEletronico.API.Models.Nota", b =>
                {
                    b.Property<int>("NotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemURl")
                        .HasColumnType("TEXT");

                    b.Property<int>("QrtCriticaNota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdNota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotaId");

                    b.ToTable("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
